### ISSUE TITLE
Working Group Proposal - Tooling

### ISSUE THREAD

**Issue by maximilien** [PQCA/TAC#14]
A working group that could create and curate CBOM (cryptography bill of material) for “important” OSS projects.

Ideally the resulting CBOM and process to create and updating the CBOM would be submitted to the upstream project. This workgroup would help create these and eventually submit to upstream.

As a suggestion, If accepted by the TAC this group could create a CBOM subproject and start collecting the projects to tackle first and creating the CBOM on project releases to get started.

Please comment here on where the state of CBOM creation and tools are and whether this working group is warranted. If we have enough interest then I will bring it up to the next TAC.

**Comment by planetf1** [comment]
* liboqs has CBOM - they are crafted carefully based on the liboqs build process. A set of yaml files describes algorithms to be retrieved from upstream sources (such as PQclean), and the CBOM is then built using these definitions (basil?)
* At the end of last year I did some scans of a few open source projects with codeQL. At the time, though I did get info about cryptographic algorithms, it was a regular sarif output, not following SBOM schema - need to look into this.
* I'm expecting scanning to be very language & ci-process specific ie per project. 
* To have a meaningfull CBOM at an application/system level, we also need the associated SBOM work to be done - for example the dependency chain. Even above hard dependencies, deployments may have specific additional 'dependencies' -- for example when using openssl, perhaps oqs-provider is installed. ... so we need to figure out the context/use cases around consuming the info
*

**Comment by planetf1** [comment]
There's lots of detail on the spec, and discussion about the importance, but unclear what tooling exists so far. A few links:

* [OWASP Blog post](https://owasp.org/blog/2023/10/03/CycloneDX-Cryptography-CBOM) (oct 23) - CycloneDX Cryptography Working Group (link to slack)
* [CBOM capability](https://cyclonedx.org/capabilities/cbom/#:~:text=A%20Cryptography%20Bill%20of%20Materials,quantum%2Dsafe%20systems%20and%20applications.) (CycloneDX)
* [cdxgen](https://github.com/CycloneDX/cdxgen) - Apache 2.0 licensed SBOM creation tool supporting many languages. **CBOM support currently only covers Java**
* [cryptobom-forge](https://github.com/Santandersecurityresearch/cryptobom-forge) - MIT licensed tool which parses CodeQL data to generate a 'CBOM' However output is in sarif format
* [codeql](https://github.blog/2023-12-05-addressing-post-quantum-cryptography-with-codeql/#:~:text=A%20CBOM%20is%20a%20record,modeling%20scope%2C%20and%20abstraction%20unification.) - Blog post on introducing CBOM support in CodeQL - but see comment above. suspected sarif format

I think one of the challenges with CBOM is many libraries will contain both qs and non qs cryptographic algorithms so it will be hard (at least from a static analysis) to determine qs or not. However it will help to provide an initial list of where crypto is used for evaluation. run-time evaluation (resolved configuration, libraries/classes loaded, network traffic analysis etc) will be needed to ascertain what is actually in use.

To move forward with this we should understand what/if any activity is going on in the openssf community, as well as any spdx/cyclonedx workgroups

**Comment by planetf1** [comment]
Update from CycloneDX:
 - [Python support has just been added](https://github.com/CycloneDX/cdxgen/pull/1026) in cdxgen
 - [Blint](https://github.com/owasp-dep-scan/blint) - work is underway to add support for rust & C

**Comment by planetf1** [comment]
No CBOM specifically, but for SBOM (may be a delta for cbom)

- [cyclonedx-rust-cargo](https://github.com/CycloneDX/cyclonedx-rust-cargo)

**Comment by planetf1** [comment]
Useful docs
 - [CycloneDX Authoritative guide](https://cyclonedx.org/guides/OWASP_CycloneDX-Authoritative-Guide-to-CBOM-en.pdf)
 - [Example BOM](https://github.com/CycloneDX/bom-examples/blob/master/CBOM/Example-With-Dependencies/bom.json)

**Comment by planetf1** [comment]
one popular open source component that can mitigate lack of PQC in other network components - ISTIO
 - Project is now generating SPDX format SBOMs - [initiative](https://docs.google.com/document/d/10ITZUUf-aGbeiBKfr-EqrQTPfPpVQmUT/edit) out of Test & Release working group
  - [2022 Presentation](https://events.istio.io/istiocon-2022/slides/g3-SupplyChainSecurity.pdf) on istio bom 
   - Latest release is [1.21.2](https://istio.io/latest/news/releases/1.21.x/announcing-1.21.2/) 
   - The [1.21.2 sbom](https://storage.googleapis.com/istio-release/releases/1.21.2/istio-release.spdx) refers to 252 'packages', though some are assemblies from others, and a lot are binaries (from the docker images)? One thing that seems absent is information about the go packages - needs more investigation in depth.
   - k8s sig has a [bom generator](https://github.com/kubernetes-sigs/bom) which includes support for go dependency analysis - spdx format

**Comment by planetf1** [comment]
* [SPDX Conversion tool](https://tools.spdx.org/app/convert/) (ie SPDX txt -> JSON) - ie open this with [JSON Viewer](https://marketplace.visualstudio.com/items?itemName=ccimage.jsonviewer). 
* no CBOM content yet

**Comment by planetf1** [comment]
Discussed in PQCA meeting 20240605 - Q: Are there github actions that can generate sbom and/or cbom free (for open source), other than codeQL (open source only).

There do seem to be a number: https://www.google.com/search?q=github+action+sbom
cc: @ryjones

**Comment by planetf1** [comment]
Opened up [issue 1831](https://github.com/open-quantum-safe/liboqs/issues/1831) in liboqs -- the cbom needs upgrading

**Comment by maximilien** [comment]
Proposal is to have "Tooling" WG

**Comment by planetf1** [comment]
I agree with the proposal

**Comment by KennyPaul** [comment]
Vote for WG creation submitted as per Sep. 10 TSC meeting

**Comment by maximilien** [comment]
Excellent. 

@n1ckl0sk0rtge was proposed as the lead for this WG
