### ISSUE TITLE
Review Lifecycle Document during TAC Call

### ISSUE THREAD

**Issue by Naomi-Wash** [PQCA/TAC#24]
### Please share any additional details on this topic

It was decided to do a live review/edit of the lifecycle document during a TAC call

### Detail what actions or feedback you would like from the TAC

N/A

### How much time do you need for this topic?

At least 30 minutes

**Comment by planetf1** [comment]
Current draft : https://docs.google.com/document/d/1NV-0vNgXWdc81oqT0jv0C-9Funb8dySS06u90ghF-X4

**Comment by maximilien** [comment]
This was done. So closing.
