### ISSUE TITLE
Project Lifecycle: API Change Procedures

### ISSUE THREAD

**Issue by Naomi-Wash** [PQCA/TAC#38]
### Comment moved from Project Lifecycle Document Section 3. Stages - Definitions & Expectations - Labs Stage - Acceptance Criteria
 Have a stable API and documentation as to API change procedures

## Discussion
> Pertains to [https://github.com/open-quantum-safe/tsc/issues/1#issuecomment-2223188200](https://www.google.com/url?q=https://github.com/open-quantum-safe/tsc/issues/1%23issuecomment-2223188200&sa=D&source=docs&ust=1723075064609422&usg=AOvVaw3XbEYFJ8M0ZoC6phdvBQyW)

**Comment by maximilien** [comment]
I believe this is solved in other issues. Let me suggest that we proactively close this issue by the next TAC meeting (Oct.9th) unless I hear otherwise..

**Comment by maximilien** [comment]
No comments then closing.
