### ISSUE TITLE
PQCA Blog: Post on mlkem-native release

### ISSUE THREAD

**Issue by hanno-becker** [PQCA/TAC#61]
The maintainers of [pqcp/mlkem-native](https://github.com/pq-code-package/mlkem-native) would like to ask the PQCA TAC to approve the publication of a short [PQCA blog](https://pqca.org/blog/) post on the recent [release of mlkem-native v1.0.0-alpha](https://github.com/pq-code-package/mlkem-native/releases/tag/v1.0.0-alpha).

The proposed text is as follows:

-------------

PQCA announces [alpha-release](https://github.com/pq-code-package/mlkem-native/releases/tag/v1.0.0-alpha) of mlkem-native
============================================

Hanno Becker (AWS), Matthias Kannwischer (Chelpis)

Earlier this year, the PQCA founded the [PQ Code Package project](https://github.com/pq-code-package) with the aim to develop production-ready, high-assurance implementations of Post-Quantum Cryptography standards. Today, we announce the first release under the PQCP: [mlkem-native v1.0.0-alpha](https://github.com/pq-code-package/mlkem-native/releases/tag/v1.0.0-alpha).

[mlkem-native](https://github.com/pq-code-package/mlkem-native) is an implementation of NIST's recent [FIPS-203 / ML-KEM](https://doi.org/10.6028/NIST.FIPS.203.ipd) Post-Quantum Cryptography standard. It is designed to be secure, fast, and easy to use: First, mlkem-native builds on the popular and time-vetted [ML-KEM reference implementation](https://github.com/pq-crystals/kyber), but is retrofitted to the C90 language standard for maximum portability. Next, we apply formal verification at the C-level to protect against common vulnerabilities such as out-of-bounds memory accesses or integer overflows. Finally, mlkem-native provides a backend interface for the seamless integration of optimized native code (e.g. assembler), and ships with high-performance backends for Arm64 and x86_64 giving it state of the art performance on most Arm64, Intel and AMD platforms. Compared to the C reference implementation, mlkem-native offers a ~3x performance improvement.

With this alpha release, we invite you to try out mlkem-native, and provide us with feedback on what we can improve to better support your use case. Please reach out by opening an [issue](https://github.com/pq-code-package/mlkem-native/issues) on the mlkem-native repository, or find us on the [PQCA Discord](https://discord.com/invite/xyVnwzfg5R).

What's next for mlkem-native? First, we plan to widen our formal verification efforts to cover functional correctness of the Arm64 and x86_64 native assembly. Second, we are working on a second external API to ML-KEM optimizing it for the common use case of ML-KEM in TLS. And finally, we are still fine-tuning performance of our native backends. So, stay tuned for more!

**Comment by planetf1** [comment]
Two suggestions
* Insert 'project' after 'founded the PQ Code Package' ?
* Make 'alpha release' a link to https://github.com/pq-code-package/mlkem-native/releases/tag/v1.0.0-alpha

**Comment by hanno-becker** [comment]
@planetf1 Done

**Comment by planetf1** [comment]
As a followup from the tac discussion 20241204, Please can I ask for reviews from:

1. The content review team. @maximilien @brian-jarvis-aws  (please indicate if you are ok with it being published)
2. Any other members of the tac including @PQCA/tac 

Ideally we'd like to publish the blog very soon - early next week, so that we can start getting feedback & spreading awareness asap.

**Comment by brian-jarvis-aws** [comment]
>ships with high-performance backends for Arm64 and x86_64 giving it state of the art performance on most Arm64, Intel and AMD platforms.

I'd like to see numbers that give some concreteness to these performance claims. Just something high level like, "that deliver a X% speedup compared to the reference implementation".

**Comment by hanno-becker** [comment]
The exact figures depend on the platform, but mlkem-native with native backends is around ~3x faster than the C reference implementation.

**Comment by hanno-becker** [comment]
We could also refer to our benchmarking page https://pq-code-package.github.io/mlkem-native/dev/bench/ -- but this only measures mlkem-native by itself, and does not give a comparison with any other implementation.

**Comment by hanno-becker** [comment]
@brian-jarvis-aws Added "Compared to the C reference implementation, mlkem-native offers a ~3x performance uplift."

**Comment by brian-jarvis-aws** [comment]
Can we say "improvement" instead of "uplift"? Other than that LGTM.

**Comment by hanno-becker** [comment]
@brian-jarvis-aws Sure, done.

**Comment by planetf1** [comment]
Looking good for myself & @brian-jarvis-aws (both on content review list). @maximilien Would you be ok to approve? If so, with 3 approvals we'd then like to proceed to publish

**Comment by maximilien** [comment]
LGTM

**Comment by hanno-becker** [comment]
@KennyPaul Are we ready to publish, then? Would you be taking care of this?

**Comment by KennyPaul** [comment]
@hanno-becker [published ](https://pqca.org/blog/2024/pqca-announces-alpha-release-of-mlkem-native/)

**Comment by SWilson4** [comment]
Closing as resolved by publication.

**Comment by fadalialbaricar-dev** [comment]
Cool
