### ISSUE TITLE
Working Group Proposal - Algorithm

### ISSUE THREAD

**Issue by maximilien** [PQCA/TAC#7]
From last week’s TAC call we agreed to propose a working group for Algorithms

Individuals interested in participating should comment on this issue for when the TAC approves this request.

**Comment by Naomi-Wash** [comment]
The TAC approved the creation of the PQCA Algorithms Working Group. A mailing list, GH repo, and a Discord channel have been created. Please be sure to subscribe/join!

Mailing List: https://lists.pqca.org/g/wg-algorithms
GH Repo: https://github.com/PQCA/wg-algorithms
Discord Channel: https://discord.com/channels/1202723482224295936/1233458593928450150

**Comment by planetf1** [comment]
See https://github.com/pq-code-package/tsc/issues/101 for a discussion we started at PQCP on additional algorithms.

**Comment by maximilien** [comment]
Closing this since PQCP is started and going strong
